name: E2E test

on:
  push:
    branches:
      - develop
      - trunk
      - smoke-testing
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - develop

jobs:
  build:
    uses: gocardless/woocommerce-gateway-gocardless/.github/workflows/generate-zip.yml@develop

  e2e:
    needs: build
    name: E2E Test
    runs-on: ubuntu-latest
    env:
      CORE_VERSION: "${{(contains(github.event.pull_request.labels.*.name, 'needs: WP RC test') && 'WordPress/WordPress#master') || 'latest'}}"

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Download build zip
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.event.repository.name }}

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ github.event.repository.name }}

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: '7.4'
          tools: composer:v2, wp

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Node cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            node_modules
            ~/.npm
          key: node-${{ hashFiles('package-lock.json') }}

      - name: Node install
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Install required WP plugins
        run: |
          URL_CONFIG="url.https://${{ secrets.BOT_GH_TOKEN }}:x-oauth-basic@github.com/.insteadOf git@github.com:"
          git config --global $URL_CONFIG
          npm run env:install-plugins
          git config --global --unset $URL_CONFIG

      - name: Set the plugin and core version config
        run: ./tests/e2e/bin/set-core-version.js --core=${{ env.CORE_VERSION }} --plugin=./${{ github.event.repository.name }}

      - name: Setup WP environment
        run: npm run env:start

      - name: Run E2E Foundational Test
        id: gocardless_e2e_tests
        run: npm run test:e2e
        env:
          GOCARDLESS_EMAIL: ${{secrets.GOCARDLESS_EMAIL}}
          GOCARDLESS_PASSWORD: ${{secrets.GOCARDLESS_PASSWORD}}

      - name: Update Success Label
        if: |
          always() &&
          steps.gocardless_e2e_tests.conclusion == 'success'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        continue-on-error: true
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['needs: e2e testing']
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['status: e2e tests passing']
            })

      - name: Update Failure Label
        if: |
          always() &&
          steps.gocardless_e2e_tests.conclusion == 'failure'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        continue-on-error: true
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['needs: e2e testing']
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['status: e2e tests failing']
            })

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: playwright-report
          path: tests/e2e/test-results/report
          retention-days: 2
