name: Build release zip

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - trunk

jobs:
  generate-zip-file:
    name: Build release zip
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup node version and npm cache
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Node dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --no-optional

      - name: Build plugin
        run: npm run build:webpack

      - name: Generate ZIP file
        uses: 10up/action-wordpress-plugin-build-zip@b9e621e1261ccf51592b6f3943e4dc4518fca0d1 # v1.0.2
